# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2155c98922e6c7902f0e632f3ce68b97e08a904a8bad94f9348fe58b30b2b5dad405fb4aab9769dda7e813f268dcf24a4fb3091d90b2b33ab23f44b0566a271d

test:
  secret_key_base: f43ec93676d58f5efe2e20a10aecebe6ae2185c4090ed50f46b15e7a3da32a4fdbc90100be1b8ddfedf97bbf85d2c07f0c1ec3780787b2c4cbb7047aa1a553ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
